# ECE2112 - Programming Assignment 2
#### Custodio, Louise Angela G.
#### 2ECE-D

## #1 NORMALIZATION PROBLEM:

In [3]:
import numpy as np

In [19]:
X = np.random.random((5,5))  
print("Original Array X:")   
print(X)   
print(" ")   

xbar = X.mean()   
print("Array X Mean: ", xbar)   
print(" ")   

sd = X.std()  
print("Array X Standard Deviation: ", sd)  
print(" ")  

Z = (X - xbar)/(sd)   
print("Normalization of X:")  
print(Z)

Original Array X:
[[0.42438587 0.71734326 0.08408038 0.49182852 0.9347497 ]
 [0.41335421 0.05811014 0.92826722 0.49749109 0.66407726]
 [0.76727938 0.15442465 0.16974381 0.66057582 0.41458171]
 [0.79330409 0.27671688 0.17745735 0.88463169 0.10160175]
 [0.50243757 0.03310108 0.93921435 0.11922228 0.9359804 ]]
 
Array X Mean:  0.48575841802328523
 
Array X Standard Deviation:  0.31296216465759247
 
Normalization of X:
[[-0.19610213  0.73997712 -1.28347155  0.01939565  1.43465037]
 [-0.23135132 -1.36645361  1.41393706  0.0374891   0.56977762]
 [ 0.89953671 -1.05870233 -1.00975338  0.55858956 -0.22742911]
 [ 0.9826928  -0.66794507 -0.98510651  1.27450957 -1.22748599]
 [ 0.05329446 -1.44636441  1.44891614 -1.17118355  1.4385828 ]]


## #2 DIVISIBLE BY 3 PROBLEM:

In [23]:
a = np.array(range(1,101))**2   
A = np.resize(a, (10,10))  
print("A = ")   
print(A)   
print(" ")   

print("Elements divisible by 3: ")  
print("B = ")   
div = A[A%3==0]   
elem = np.resize(div, (3,11))   
print(elem)   

A = 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
 
Elements divisible by 3: 
B = 
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
