# ECE2112 - Programming Assignment 2
#### Custodio, Louise Angela G.
#### 2ECE-D

## #1 NORMALIZATION PROBLEM:

Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. 

Expected Input: 
A randomly generated 5x5 NumPy array of float values between 0 and 1. The first matrix represents the original dataset 𝑋. 

(Note: There is no manual input as the matrix will be randomly generated.)

Expected Output: 
A normalized 5x5 NumPy array where each value is normalized according to the formula 𝑍 = (𝑋-𝑥bar)/𝜎, with a mean of 0 and a standard deviation of 1.

In [5]:
import numpy as np

In [6]:
X = np.random.random((5,5))  
print("Original Array X:")   
print(X)   
print(" ")   

xbar = X.mean()   
print("Array X Mean: ", xbar)   
print(" ")   

sd = X.std()  
print("Array X Standard Deviation: ", sd)  
print(" ")  

Z = (X - xbar)/(sd)   

np.save('X_normalized.npy', Z)
np.load('X_normalized.npy')

Original Array X:
[[0.33752359 0.58869063 0.94416827 0.88885209 0.68664553]
 [0.90884864 0.24662983 0.08046505 0.77448618 0.10022813]
 [0.99257561 0.74430729 0.63631818 0.26872616 0.27948361]
 [0.23411741 0.47050027 0.51777925 0.01003791 0.48243333]
 [0.1116851  0.36563682 0.70776885 0.33803747 0.47704102]]
 
Array X Mean:  0.48771945010751083
 
Array X Standard Deviation:  0.2849828295838069
 


array([[-0.52703477,  0.35430619,  1.60167131,  1.40756776,  0.69802831],
       [ 1.47773533, -0.84597946, -1.42904889,  1.00625969, -1.35970058],
       [ 1.77153186,  0.90036244,  0.52143046, -0.7684438 , -0.7306961 ],
       [-0.88988534, -0.06042182,  0.10547935, -1.67617656, -0.0185489 ],
       [-1.31949825, -0.42838591,  0.77214969, -0.52523157, -0.03747042]])

## #2 DIVISIBLE BY 3 PROBLEM:

The task involves creating a 10x10 NumPy array 𝐴, where each element represents the square of the first 100 positive integers. 
From this array, the elements divisible by 3 must be identified.

Expected Input: 
A 10x10 NumPy array A where each element is the square of the first 100 positive integers that range to 1-1000.

(Note: There is no manual input as the first 100 positive integers will be automatically squared.)

Expected Output: 
A NumPy array containing only the elements from the input that are divisible by 3.

In [10]:
a = np.array(range(1,101))**2   
A = np.resize(a, (10,10))  
print("A = ")   
print(A)    
  
div = A[A % 3 == 0]     

np.save('div_by_3.npy', div)
np.load('div_by_3.npy')

A = 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])