## EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

#### Custodio, Louise Angela G.
#### 2ECE-D

### #1 NORMALIZATION PROBLEM:

Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. 

Expected Input: 
A randomly generated 5x5 NumPy array of float values between 0 and 1. The first matrix represents the original dataset 𝑋. 

(Note: There is no manual input as the matrix will be randomly generated.)

Expected Output: 
A normalized 5x5 NumPy array where each value is normalized according to the formula 𝑍 = (𝑋-𝑥bar)/𝜎, with a mean of 0 and a standard deviation of 1.

In [6]:
import numpy as np

In [16]:
X = np.random.random((5,5))  
print("Original Array X:")   
print(X)   
print(" ")   

xbar = X.mean()   
print("Array X Mean: ", xbar)   
print(" ")   

sd = X.std()  
print("Array X Standard Deviation: ", sd)  
print(" ")  

Z = (X - xbar)/(sd)   

np.save('X_normalized.npy', Z)
np.load('X_normalized.npy')

Original Array X:
[[0.18660008 0.80903505 0.09512125 0.91850667 0.4150998 ]
 [0.12586578 0.0404285  0.004406   0.76892848 0.72464762]
 [0.78953472 0.58710837 0.21462462 0.68755254 0.24650941]
 [0.69722387 0.36428258 0.90673319 0.05388998 0.62391131]
 [0.85955114 0.62676179 0.92699266 0.77023552 0.71430906]]
 
Array X Mean:  0.526314399000223
 
Array X Standard Deviation:  0.30972954224961124
 


array([[-1.09680954,  0.91279846, -1.39216023,  1.2662411 , -0.35907005],
       [-1.29289772, -1.56874251, -1.6850456 ,  0.78330946,  0.64034323],
       [ 0.84983925,  0.19628083, -1.00632887,  0.52057719, -0.9033849 ],
       [ 0.5518023 , -0.52313969,  1.22822896, -1.52528045,  0.31510364],
       [ 1.07589587,  0.32430678,  1.29363916,  0.78752939,  0.60696393]])