## EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

#### Custodio, Louise Angela G.
#### 2ECE-D

### #1 NORMALIZATION PROBLEM:

Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. 

Expected Input: 
A randomly generated 5x5 NumPy array of float values between 0 and 1. The first matrix represents the original dataset 𝑋. 

(Note: There is no manual input as the matrix will be randomly generated.)

Expected Output: 
A normalized 5x5 NumPy array where each value is normalized according to the formula 𝑍 = (𝑋-𝑥bar)/𝜎, with a mean of 0 and a standard deviation of 1.

In [6]:
import numpy as np

In [12]:
X = np.random.random((5,5))  
print("Original Array X:")   
print(X)   
print(" ")   

xbar = X.mean()   
print("Array X Mean: ", xbar)   
print(" ")   

sd = X.std()  
print("Array X Standard Deviation: ", sd)  
print(" ")  

Z = (X - xbar)/(sd)   
print("Normalization of X:")  
print(Z)

np.save('X_normalized.npy',Z)
np.load('X_normalized.npy')

Original Array X:
[[0.893601   0.22427361 0.78546893 0.23746517 0.57598927]
 [0.94757641 0.28352797 0.34391067 0.33357342 0.23646142]
 [0.96093347 0.02286107 0.10922931 0.11797436 0.93736366]
 [0.26939188 0.62803367 0.60333938 0.96777943 0.66994032]
 [0.27242256 0.22769227 0.08710636 0.84997719 0.85949039]]
 
Array X Mean:  0.4978153280710584
 
Array X Standard Deviation:  0.3201163567560161
 
Normalization of X:
[[ 1.23638065 -0.85450716  0.89859077 -0.81329851  0.24420478]
 [ 1.40499249 -0.66940458 -0.48077724 -0.5130694  -0.81643408]
 [ 1.44671816 -1.48369257 -1.21388991 -1.18657158  1.37308927]
 [-0.71356382  0.4067844   0.32964279  1.46810401  0.53769509]
 [-0.70409637 -0.84382773 -1.28299902  1.10010581  1.12982375]]


array([[ 1.23638065, -0.85450716,  0.89859077, -0.81329851,  0.24420478],
       [ 1.40499249, -0.66940458, -0.48077724, -0.5130694 , -0.81643408],
       [ 1.44671816, -1.48369257, -1.21388991, -1.18657158,  1.37308927],
       [-0.71356382,  0.4067844 ,  0.32964279,  1.46810401,  0.53769509],
       [-0.70409637, -0.84382773, -1.28299902,  1.10010581,  1.12982375]])